text-rewriter/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'texts#index'
  resources :texts, only: [:index]
  get '/paraphrase', to: "texts#rewrite_text"
  get '/show-texts', to: "texts#show_texts"
  get 'delete-texts', to: "texts#delete_texts"
end

text-rewriter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

text-rewriter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

text-rewriter/app/controllers/texts_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
require'json'

class TextsController < ApplicationController
  @@parsed_texts = []

  def index
  end

  def rewrite_text
    paraphrased_text = api_call(params[:paraphrase][:text])
    @@parsed_texts << paraphrased_text
    redirect_to texts_path
  end


  def show_texts
    @texts = @@parsed_texts
  end

  def delete_texts
    @@parsed_texts.clear
    redirect_to texts_path
  end

  private

  def api_call(text)
    url = URI("https://rewriter-paraphraser-text-changer-multi-language.p.rapidapi.com/rewrite")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Post.new(url)
    request["content-type"] = 'application/json'
    request["x-rapidapi-key"] = '0ff14fe9e7msh77b3e0c40e4e814p1d4094jsn1d9333d48168'
    request["x-rapidapi-host"] = 'rewriter-paraphraser-text-changer-multi-language.p.rapidapi.com'
    request.body = "{
        \"language\": \"en\",
        \"strength\": 3,
        \"text\": \"#{text}\"
    }"
    response = http.request(request)
    parsed = JSON.parse(response.body)
  return parsed["rewrite"]
  end
end

text-rewriter/app/helpers/application_helper.rb
module ApplicationHelper
end

text-rewriter/app/helpers/texts_helper.rb
module TextsHelper
end

text-rewriter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextRewriter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

text-rewriter/app/views/texts/index.html.erb
<h1>Praphrasing Tool</h1>

<h2>Please input the texts you would like to paraphrase</h2>
  <%= simple_form_for :paraphrase, url: paraphrase_path, :method => 'get' do |f| %>
    <%= f.input :text, as: :text%>
    <%= f.button :submit, "Submit" %>
  <% end %>

  <br>

  <h2>Please click here if you are done submitting your texts</h2>
  <%= link_to "Done!", show_texts_path %>

  <h2>Please click here if you would like to delete all the submitted texts!</h2>
  <%= link_to "Delete", delete_texts_path %>

text-rewriter/app/views/texts/show_texts.html.erb
<h1>Here are your paraphrased texts</h1>

<% if @texts.empty? %>
<h2>You have not added some texts to paraphrase!</h2>
<% end  %>

<% @texts.each do |text| %>
<%= text %>
<% end %>